#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
STATE_DIR="${STATE_DIR:-$(cd "$SCRIPT_DIR/.." && pwd)}"
ENVF="${ENVF:-$STATE_DIR/.env}"
VHOST_DIR="${VHOST_DIR:-$STATE_DIR/vhost.d}"

source "$SCRIPT_DIR/utils.sh"

require_file "$ENVF" ".env not found"
mkdir -p "$VHOST_DIR"

set -a
. "$ENVF"
set +a

require_var APP_DOMAIN
require_var API_DOMAIN

LEGACY_TLS_HOSTS="${LEGACY_TLS_HOSTS:-}"
LEGACY_TLS_PROTOCOLS="${LEGACY_TLS_PROTOCOLS:-TLSv1 TLSv1.1 TLSv1.2 TLSv1.3}"
LEGACY_TLS_CIPHERS="${LEGACY_TLS_CIPHERS:-ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-RSA-AES128-SHA:ECDHE-RSA-AES256-SHA:AES128-SHA:AES256-SHA}"

csv_contains() {
  local needle="${1,,}"
  local haystack="${2:-}"
  local item trimmed
  IFS=',' read -r -a items <<<"$haystack"
  for item in "${items[@]}"; do
    trimmed="$(echo "$item" | xargs)"
    if [[ "${trimmed,,}" == "$needle" ]]; then
      return 0
    fi
  done
  return 1
}

render_tls_file() {
  local host="$1"
  local target="$VHOST_DIR/$host.tls"

  if csv_contains "$host" "$LEGACY_TLS_HOSTS"; then
    cat >"$target" <<EOF
# Generated by scripts/render_tls_overrides.sh
# Legacy TLS compatibility is enabled for ${host}.
ssl_protocols ${LEGACY_TLS_PROTOCOLS};
ssl_ciphers '${LEGACY_TLS_CIPHERS}';
ssl_prefer_server_ciphers on;
ssl_ecdh_curve X25519:prime256v1:secp384r1;
EOF
    echo "[tls] legacy profile enabled for ${host}"
    return 0
  fi

  cat >"$target" <<EOF
# Generated by scripts/render_tls_overrides.sh
# Legacy TLS compatibility is disabled for ${host}.
EOF
  echo "[tls] legacy profile disabled for ${host}"
}

render_tls_file "$APP_DOMAIN"
render_tls_file "$API_DOMAIN"
