#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
DEFAULT_ENV_FILE="$(cd "$SCRIPT_DIR/.." && pwd)/deployment/.env"
ENV_FILE="${1:-$DEFAULT_ENV_FILE}"

if ! command -v openssl >/dev/null 2>&1; then
    echo "[error] openssl is required but not installed." >&2
    echo "Install openssl (apt install openssl) and re-run this script." >&2
    exit 1
fi

# normalise env file path
ENV_FILE="$(python - <<'PY' "$ENV_FILE"
import os, sys
print(os.path.abspath(sys.argv[1]))
PY
)"

if [ ! -f "$ENV_FILE" ]; then
    echo "[info] environment file '$ENV_FILE' not found."
    read -r -p "Create an empty env file at this location? [y/N] " reply
    if [[ "$reply" =~ ^[Yy]$ ]]; then
        mkdir -p "$(dirname "$ENV_FILE")"
        printf "# generated by check_certs.sh on %s\n" "$(date -Iseconds)" > "$ENV_FILE"
    else
        echo "Aborting. Provide the env file path as the first argument if it lives elsewhere."
        exit 1
    fi
fi

backup="$ENV_FILE.bak.$(date +%s)"
cp "$ENV_FILE" "$backup"
echo "[info] Created backup: $backup"

# helpers ---------------------------------------------------------------

get_env_value() {
    local key="$1"
    grep -E "^${key}=" "$ENV_FILE" | tail -n1 | cut -d= -f2-
}

set_env_value() {
    local key="$1" value="$2"
    local tmp
    tmp="$(mktemp)"
    if grep -q "^${key}=" "$ENV_FILE"; then
        awk -v k="$key" -v v="$value" 'BEGIN{updated=0} {
            if ($0 ~ "^" k "=") { print k "=" v; updated=1 } else { print $0 }
        } END { if (!updated) print k "=" v }' "$ENV_FILE" > "$tmp"
    else
        cat "$ENV_FILE" > "$tmp"
        printf "%s=%s\n" "$key" "$value" >> "$tmp"
    fi
    mv "$tmp" "$ENV_FILE"
}

ensure_env_path() {
    local key="$1" default_path="$2" prompt="$3"
    local current
    current="$(get_env_value "$key")"
    if [[ -n "$current" ]]; then
        echo "[info] $key=$current"
        printf '%s' "$current"
        return 0
    fi
    echo "[prompt] $prompt"
    read -r -p "$key [$default_path]: " answer
    answer="${answer:-$default_path}"
    set_env_value "$key" "$answer"
    echo "[info] Set $key=$answer"
    printf '%s' "$answer"
}

ensure_directory() {
    local path="$1"
    local dir
    dir="$(dirname "$path")"
    if [ ! -d "$dir" ]; then
        mkdir -p "$dir"
    fi
}

check_cert_validity() {
    local cert="$1" days="$2"
    if [ ! -f "$cert" ]; then
        return 1
    fi
    if openssl x509 -checkend "$((days*24*60*60))" -noout -in "$cert" >/dev/null 2>&1; then
        return 0
    fi
    return 1
}

# determine defaults ----------------------------------------------------
ENV_DIR="$(dirname "$ENV_FILE")"
DEFAULT_CERT_DIR="$ENV_DIR/dev-secrets"

CA_KEY_DEFAULT="$DEFAULT_CERT_DIR/ca.key"
CA_CERT_DEFAULT="$DEFAULT_CERT_DIR/ca.crt"
TLS_KEY_DEFAULT="$DEFAULT_CERT_DIR/server.key"
TLS_CERT_DEFAULT="$DEFAULT_CERT_DIR/server.crt"

ca_key_path="$(ensure_env_path "CA_KEY_PEM_FILE" "$CA_KEY_DEFAULT" "Path to CA private key (PEM)")"
ca_cert_path="$(ensure_env_path "CA_CERT_PEM_FILE" "$CA_CERT_DEFAULT" "Path to CA certificate (PEM)")"
tls_key_path="$(ensure_env_path "TLS_KEY_PEM_FILE" "$TLS_KEY_DEFAULT" "Path to TLS server private key (PEM)")"
tls_cert_path="$(ensure_env_path "TLS_CERT_PEM_FILE" "$TLS_CERT_DEFAULT" "Path to TLS server certificate (PEM)")"

ensure_directory "$ca_key_path"
ensure_directory "$ca_cert_path"
ensure_directory "$tls_key_path"
ensure_directory "$tls_cert_path"

# CA generation ---------------------------------------------------------
if [ ! -s "$ca_key_path" ] || [ ! -s "$ca_cert_path" ]; then
    echo "[info] CA material missing at $ca_key_path / $ca_cert_path"
    read -r -p "Generate new development CA now? [Y/n] " reply
    if [[ ! "$reply" =~ ^[Nn]$ ]]; then
        openssl genrsa -out "$ca_key_path" 4096
        chmod 600 "$ca_key_path"
        openssl req -x509 -new -sha256 \
            -days 730 \
            -key "$ca_key_path" \
            -config "$SCRIPT_DIR/mini-openssl.cnf" \
            -out "$ca_cert_path"
        echo "[ok] Generated CA key and certificate."
    else
        echo "[warn] Provide CA artifacts manually (expected from /opt/inimatic/secrets/ca.{key,crt})."
    fi
else
    echo "[ok] CA material already present."
fi

# TLS generation --------------------------------------------------------
regenerate_tls=0
if [ ! -s "$tls_key_path" ] || [ ! -s "$tls_cert_path" ]; then
    regenerate_tls=1
else
    if ! check_cert_validity "$tls_cert_path" 30; then
        echo "[warn] TLS certificate expires within 30 days."
        read -r -p "Regenerate TLS certificate using local CA? [Y/n] " answer
        if [[ ! "$answer" =~ ^[Nn]$ ]]; then
            regenerate_tls=1
        fi
    else
        echo "[ok] TLS certificate is present and valid."
    fi
fi

if [ "$regenerate_tls" -eq 1 ]; then
    read -r -p "Common Name for TLS certificate [api.inimatic.com]: " cn
    cn="${cn:-api.inimatic.com}"
    tmp_conf="$(mktemp)"
    tmp_csr="$(mktemp)"
    cat > "$tmp_conf" <<CONF
[ req ]
prompt = no
distinguished_name = dn
req_extensions = v3_req

[ dn ]
CN = $cn
O = Inimatic Root

[ v3_req ]
subjectAltName = @alt_names
extendedKeyUsage = serverAuth
keyUsage = critical, digitalSignature, keyEncipherment

[ alt_names ]
DNS.1 = $cn
DNS.2 = localhost
IP.1 = 127.0.0.1
CONF
    openssl genrsa -out "$tls_key_path" 4096
    chmod 600 "$tls_key_path"
    openssl req -new -key "$tls_key_path" -out "$tmp_csr" -config "$tmp_conf"
    openssl x509 -req -in "$tmp_csr" -CA "$ca_cert_path" -CAkey "$ca_key_path" -CAcreateserial \
        -out "$tls_cert_path" -days 365 -sha256 -extensions v3_req -extfile "$tmp_conf"
    rm -f "$tmp_conf" "$tmp_csr"
    echo "[ok] Generated TLS key and certificate signed by local CA."
fi

# Inline PEM hints ------------------------------------------------------
for inline_var in CA_KEY_PEM CA_CERT_PEM TLS_KEY_PEM TLS_CERT_PEM; do
    if [[ -n "$(get_env_value "$inline_var")" ]]; then
        echo "[warn] $inline_var is set in .env. Ensure it matches files referenced via ${inline_var}_FILE."
    fi
done

echo "[done] Certificate check complete. Update $ENV_FILE if manual adjustments are required."
echo "[hint] For production secrets reference /opt/inimatic/secrets or consult infra runbooks."
