// Auto-generated by scripts/gen-build-info.mjs
export const buildId: string = "local-1774414193181"
export const buildVersion: string = "0.0.1+local-1774414193181"
export const buildTime: string = "2026-03-25T04:49:53.181Z"
