// Auto-generated by scripts/gen-build-info.mjs
export const buildId: string = "local-1774862596870"
export const buildVersion: string = "0.0.1+local-1774862596870"
export const buildTime: string = "2026-03-30T09:23:16.870Z"
