import { addIcons } from 'ionicons'
import {
  addOutline,
  alertCircleOutline,
  arrowBackOutline,
  arrowForwardOutline,
  lockClosedOutline,
  checkmarkOutline,
  chevronDownOutline,
  chevronUpOutline,
  closeOutline,
  cloudDoneOutline,
  people,
  peopleOutline,
  personOutline,
  phonePortrait,
  apps,
  laptop,
  desktop,
  desktopOutline,
  settings,
  settingsOutline,
  close,
  codeOutline,
  cogOutline,
  image,
  camera,
  refresh,
  refreshOutline,
  cloudOutline,
  documentTextOutline,
  downloadOutline,
  flashOutline,
  folderOpenOutline,
  gitNetworkOutline,
  hardwareChipOutline,
  helpCircleOutline,
  homeOutline,
  informationCircleOutline,
  layersOutline,
  listOutline,
  logOutOutline,
  mailOutline,
  menuOutline,
  micOutline,
  playOutline,
  radioOutline,
  rocketOutline,
  schoolOutline,
  searchOutline,
  sendOutline,
  serverOutline,
  statsChartOutline,
  terminalOutline,
  appsOutline,
  bookmarkOutline,
  contractOutline,
  expandOutline,
  videocamOutline,
  warningOutline,
} from 'ionicons/icons'

export function registerIcons(): void {
  addIcons({
    'add-outline': addOutline,
    'alert-circle-outline': alertCircleOutline,
    'arrow-back-outline': arrowBackOutline,
    'arrow-forward-outline': arrowForwardOutline,
    'lock-closed-outline': lockClosedOutline,
    'checkmark-outline': checkmarkOutline,
    'chevron-down-outline': chevronDownOutline,
    'chevron-up-outline': chevronUpOutline,
    'close-outline': closeOutline,
    'cloud-done-outline': cloudDoneOutline,
    people,
    'people-outline': peopleOutline,
    'person-outline': personOutline,
    'phone-portrait': phonePortrait,
    apps,
    laptop,
    desktop,
    'desktop-outline': desktopOutline,
    settings,
    'settings-outline': settingsOutline,
    close,
    'code-outline': codeOutline,
    'cog-outline': cogOutline,
    image,
    camera,
    refresh,
    'refresh-outline': refreshOutline,
    'cloud-outline': cloudOutline,
    'document-text-outline': documentTextOutline,
    'download-outline': downloadOutline,
    'flash-outline': flashOutline,
    'folder-open-outline': folderOpenOutline,
    'git-network-outline': gitNetworkOutline,
    'hardware-chip-outline': hardwareChipOutline,
    'help-circle-outline': helpCircleOutline,
    'home-outline': homeOutline,
    'information-circle-outline': informationCircleOutline,
    'layers-outline': layersOutline,
    'list-outline': listOutline,
    'log-out-outline': logOutOutline,
    'mail-outline': mailOutline,
    'menu-outline': menuOutline,
    'mic-outline': micOutline,
    'play-outline': playOutline,
    'radio-outline': radioOutline,
    'rocket-outline': rocketOutline,
    'school-outline': schoolOutline,
    'search-outline': searchOutline,
    'send-outline': sendOutline,
    'server-outline': serverOutline,
    'stats-chart-outline': statsChartOutline,
    'terminal-outline': terminalOutline,
    'apps-outline': appsOutline,
    'bookmark-outline': bookmarkOutline,
    'contract-outline': contractOutline,
    'expand-outline': expandOutline,
    'videocam-outline': videocamOutline,
    'warning-outline': warningOutline,
  })
}
